-- 7Metros — BORRADOR NO APLICADO
-- Persistencia explícita para ajustes administrativos de posiciones.
--
-- Este archivo vive deliberadamente fuera de supabase/migrations/.
-- NO aplicar a producción hasta probarlo en una rama/staging de Supabase,
-- ejecutar advisors e integrity_report_7metros, y generar luego una migración
-- oficial con el flujo de Supabase CLI.
--
-- Principios:
-- - nunca inferir sanciones desde marcadores, fixtures vencidos o planillas ausentes;
-- - ajustes append-only: no UPDATE/DELETE para roles de aplicación;
-- - toda fila exige fuente oficial, motivo, fecha de resolución e idempotency key;
-- - el equipo debe pertenecer a la temporada y la temporada a la competencia;
-- - una reversión es otra fila explícita, del mismo scope/equipo y delta opuesto;
-- - anon/authenticated no tienen acceso directo.

begin;

create table if not exists public.administrative_standings_adjustments (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.equipos(id) on delete restrict,
  season_id bigint not null references public.temporadas(id) on delete restrict,
  competition_id bigint not null references public.competencias(id) on delete restrict,
  points_delta integer not null check (points_delta <> 0),
  reason text not null check (btrim(reason) <> ''),
  official_source text not null check (
    btrim(official_source) <> ''
    and official_source ~ '^https://[^[:space:]]+$'
  ),
  resolution_date date not null,
  source_record_key text not null check (btrim(source_record_key) <> ''),
  reversal_of_id bigint unique references public.administrative_standings_adjustments(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint administrative_standings_adjustments_source_key_unique unique (source_record_key)
);

create index if not exists idx_admin_standings_adjustments_scope
  on public.administrative_standings_adjustments(season_id, competition_id, team_id);

create or replace function public.validate_administrative_standings_adjustment_scope()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_team_season_id bigint;
  v_season_competition_id bigint;
  v_original public.administrative_standings_adjustments%rowtype;
begin
  select e.temporada_id
    into v_team_season_id
  from public.equipos e
  where e.id = new.team_id;

  if v_team_season_id is null then
    raise exception 'team_id % inexistente', new.team_id;
  end if;

  if v_team_season_id <> new.season_id then
    raise exception 'team_id % no pertenece a season_id %', new.team_id, new.season_id;
  end if;

  select t.competencia_id
    into v_season_competition_id
  from public.temporadas t
  where t.id = new.season_id;

  if v_season_competition_id is null then
    raise exception 'season_id % inexistente', new.season_id;
  end if;

  if v_season_competition_id <> new.competition_id then
    raise exception 'season_id % no pertenece a competition_id %', new.season_id, new.competition_id;
  end if;

  if new.reversal_of_id is not null then
    select *
      into v_original
    from public.administrative_standings_adjustments a
    where a.id = new.reversal_of_id;

    if not found then
      raise exception 'reversal_of_id % inexistente', new.reversal_of_id;
    end if;

    if v_original.team_id <> new.team_id
       or v_original.season_id <> new.season_id
       or v_original.competition_id <> new.competition_id then
      raise exception 'la reversión debe conservar team/season/competition del ajuste original';
    end if;

    if v_original.points_delta + new.points_delta <> 0 then
      raise exception 'la reversión debe tener delta exactamente opuesto al ajuste original';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function public.validate_administrative_standings_adjustment_scope() from public, anon, authenticated;

create trigger trg_validate_administrative_standings_adjustment_scope
before insert on public.administrative_standings_adjustments
for each row execute function public.validate_administrative_standings_adjustment_scope();

alter table public.administrative_standings_adjustments enable row level security;

revoke all on table public.administrative_standings_adjustments from public, anon, authenticated;
revoke all on table public.administrative_standings_adjustments from service_role;
grant select, insert on table public.administrative_standings_adjustments to service_role;

-- Sin políticas RLS para anon/authenticated: fail-closed por defecto.
-- No se concede UPDATE/DELETE: correcciones se registran mediante reversión explícita.

commit;
