const STORAGE_KEY='7m_vision_api';
const DEFAULT_API='http://127.0.0.1:8000';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let store=null;

function apiBase(){return ($('#vision-api-url')?.value||localStorage.getItem(STORAGE_KEY)||DEFAULT_API).replace(/\/$/,'')}
function setStatus(mode,text){const el=$('#vision-api-pill');if(!el)return;el.className=`vision-status ${mode}`;el.textContent=text}
function message(text,kind=''){const el=$('#vision-message');el.textContent=text;el.className=`vision-message ${kind}`}
async function api(path,opts={}){const r=await fetch(`${apiBase()}${path}`,opts);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||`HTTP ${r.status}`);return data}

async function health(){setStatus('checking','Comprobando API…');try{const h=await api('/api/v1/health');setStatus('online',`API conectada · v${h.version}`);await loadCapabilities();await loadJobs();return true}catch(e){setStatus('offline','Backend no conectado');$('#vision-capabilities').innerHTML='<div class="vision-empty">El frontend funciona, pero el backend local/servidor no está disponible.</div>';return false}}
async function loadCapabilities(){const c=await api('/api/v1/capabilities');const labels={players:'Jugadores',multi_object_tracking:'Tracking multiobjeto',ball_tracking:'Tracking de pelota',team_classification:'Clasificación de equipo',roster_identity_resolution:'Resolución contra plantel',event_candidates:'Eventos candidatos',selective_rescue_scheduler:'Rescate selectivo',offline_global_association:'Asociación global offline',temporal_ball_model:'Modelo temporal pelota',rfdetr_adapter:'RF-DETR',real_handball_benchmark:'Benchmark real'};$('#vision-capabilities').innerHTML=Object.entries(labels).map(([k,label])=>{const v=c[k];const ok=v===true;return `<div class="vision-cap"><span>${esc(label)}</span><b class="${ok?'yes':'pending'}">${ok?'LISTO':esc(String(v??'pendiente').replaceAll('_',' ')).toUpperCase()}</b></div>`}).join('')}

async function waitForStore(){for(let i=0;i<80;i++){try{store=await import('./store.js');if(store.state.loaded)return}catch{}await new Promise(r=>setTimeout(r,100))}}
function populateMatches(){const sel=$('#vision-match');if(!store?.state?.matches?.length)return;const rows=[...store.state.matches].sort((a,b)=>String(b.date).localeCompare(String(a.date)));for(const m of rows)sel.insertAdjacentHTML('beforeend',`<option value="${m.id}">${esc(m.date||'')} · ${esc(m.home)} vs ${esc(m.away)}</option>`);sel.addEventListener('change',renderRosterContext);renderRosterContext()}
function renderRosterContext(){const id=Number($('#vision-match').value);const m=store?.state?.index?.matchById?.get(id);const el=$('#vision-roster-context');if(!m){el.textContent='El análisis puede ejecutarse sin asociarlo a un partido.';return}const home=store.state.index.rosterByTeam.get(Number(m.homeTeamId))||[];const away=store.state.index.rosterByTeam.get(Number(m.awayTeamId))||[];el.innerHTML=`<b>${esc(m.home)}</b>: ${home.length} jugadores en plantel · <b>${esc(m.away)}</b>: ${away.length} jugadores. Este contexto permitirá resolver dorsal + equipo → jugador real.`}

async function runAnalysis(){const file=$('#vision-file').files?.[0];if(!file){message('Seleccioná un archivo de video.','error');return}localStorage.setItem(STORAGE_KEY,apiBase());const ok=await health();if(!ok){message('No puedo iniciar el análisis porque el backend no está conectado.','error');return}const fd=new FormData();fd.append('file',file);fd.append('engine',$('#vision-engine').value);if($('#vision-match').value)fd.append('match_id',$('#vision-match').value);if($('#vision-max-frames').value)fd.append('max_frames',$('#vision-max-frames').value);const btn=$('#vision-run');btn.disabled=true;message('Analizando. En esta versión la solicitud espera a que termine el trabajo…');try{const job=await api('/api/v1/analyze',{method:'POST',body:fd});message('Análisis finalizado y persistido.','ok');await showJob(job.id);await loadJobs()}catch(e){message(e.message,'error')}finally{btn.disabled=false}}
function kpi(label,value){return `<div class="vision-kpi"><small>${esc(label)}</small><b>${esc(value??'—')}</b></div>`}
async function showJob(id){const j=await api(`/api/v1/jobs/${encodeURIComponent(id)}`);$('#vision-result-title').textContent=`Trabajo ${id.slice(0,8)}`;$('#vision-job-status').textContent=(j.status||'—').toUpperCase();const s=j.summary||{};$('#vision-kpis').innerHTML=kpi('Frames',s.frames)+kpi('Observ. jugador',s.player_observations)+kpi('IDs',s.unique_player_ids)+kpi('Frames pelota',s.ball_frames)+kpi('Eventos',s.events);const v=$('#vision-video');if(j.status==='done'&&j.output_video){v.src=`${apiBase()}/api/v1/jobs/${encodeURIComponent(id)}/video`;v.hidden=false}else{v.hidden=true;v.removeAttribute('src')}let events=[];try{events=(await api(`/api/v1/jobs/${encodeURIComponent(id)}/events`)).items}catch{}$('#vision-events').innerHTML=events.length?events.map(e=>`<div class="vision-event"><code>F${e.frame}</code><b>${esc(e.event_type)}</b><span>${Math.round((e.confidence||0)*100)}%</span></div>`).join(''):'<div class="vision-empty">Sin eventos candidatos guardados.</div>'}
async function loadJobs(){try{const rows=(await api('/api/v1/jobs?limit=12')).items;$('#vision-jobs').innerHTML=rows.length?rows.map(j=>`<div class="vision-job"><code>${esc(j.created_at||'')}</code><button type="button" data-job="${esc(j.id)}">${esc((j.input_name||j.id).slice(0,52))}</button><span class="status-pill">${esc((j.status||'').toUpperCase())}</span></div>`).join(''):'<div class="vision-empty">Todavía no hay trabajos.</div>';document.querySelectorAll('[data-job]').forEach(b=>b.addEventListener('click',()=>showJob(b.dataset.job)))}catch{$('#vision-jobs').innerHTML='<div class="vision-empty">Backend no disponible.</div>'}}

$('#vision-api-url').value=localStorage.getItem(STORAGE_KEY)||DEFAULT_API;
$('#vision-api-url').addEventListener('change',()=>{localStorage.setItem(STORAGE_KEY,apiBase());health()});
$('#vision-refresh').addEventListener('click',health);$('#vision-jobs-refresh').addEventListener('click',loadJobs);$('#vision-run').addEventListener('click',runAnalysis);
waitForStore().then(populateMatches);health();
