-- 7Metros platform hardening + analytics
-- Applied to Supabase project 7Metros on 2026-09-09.
-- Keep this file as the repository source of truth for the production migration.

begin;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.es_admin()
returns boolean language sql stable security definer
set search_path = pg_catalog, public
as $$ select exists (select 1 from public.perfiles where id=auth.uid() and rol='admin' and activo=true); $$;

create or replace function private.es_colaborador()
returns boolean language sql stable security definer
set search_path = pg_catalog, public
as $$ select exists (select 1 from public.perfiles where id=auth.uid() and rol in ('admin','colaborador','analista') and activo=true); $$;

revoke all on function private.es_admin() from public;
revoke all on function private.es_colaborador() from public;
grant execute on function private.es_admin() to authenticated;
grant execute on function private.es_colaborador() to authenticated;

create or replace function public.es_admin()
returns boolean language sql stable security invoker
set search_path = pg_catalog, public, private
as $$ select private.es_admin(); $$;

create or replace function public.es_colaborador()
returns boolean language sql stable security invoker
set search_path = pg_catalog, public, private
as $$ select private.es_colaborador(); $$;

revoke all on function public.es_admin() from public;
revoke all on function public.es_colaborador() from public;
grant execute on function public.es_admin() to authenticated;
grant execute on function public.es_colaborador() to authenticated;

create table if not exists public.jugador_aliases (
  id bigint generated by default as identity primary key,
  jugador_id bigint not null references public.jugadores(id) on delete cascade,
  alias text not null,
  alias_normalizado text not null unique,
  fuente text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists idx_jugador_aliases_jugador on public.jugador_aliases(jugador_id);
alter table public.jugador_aliases enable row level security;
drop policy if exists jugador_aliases_select_colaborador on public.jugador_aliases;
create policy jugador_aliases_select_colaborador on public.jugador_aliases for select to authenticated using (public.es_colaborador());
drop policy if exists jugador_aliases_insert_admin on public.jugador_aliases;
create policy jugador_aliases_insert_admin on public.jugador_aliases for insert to authenticated with check (public.es_admin());
drop policy if exists jugador_aliases_update_admin on public.jugador_aliases;
create policy jugador_aliases_update_admin on public.jugador_aliases for update to authenticated using (public.es_admin()) with check (public.es_admin());
drop policy if exists jugador_aliases_delete_admin on public.jugador_aliases;
create policy jugador_aliases_delete_admin on public.jugador_aliases for delete to authenticated using (public.es_admin());
grant select,insert,update,delete on public.jugador_aliases to authenticated;

create table if not exists public.import_runs (
  id bigint generated by default as identity primary key,
  tipo text not null,
  fuente text,
  estado text not null default 'pendiente' check (estado in ('pendiente','ejecutando','completado','parcial','error')),
  registros_leidos integer not null default 0 check (registros_leidos>=0),
  registros_insertados integer not null default 0 check (registros_insertados>=0),
  registros_actualizados integer not null default 0 check (registros_actualizados>=0),
  errores integer not null default 0 check (errores>=0),
  detalle jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists idx_import_runs_estado_started on public.import_runs(estado,started_at desc);
alter table public.import_runs enable row level security;
drop policy if exists import_runs_select_colaborador on public.import_runs;
create policy import_runs_select_colaborador on public.import_runs for select to authenticated using (public.es_colaborador());
drop policy if exists import_runs_insert_colaborador on public.import_runs;
create policy import_runs_insert_colaborador on public.import_runs for insert to authenticated with check (public.es_colaborador());
drop policy if exists import_runs_update_colaborador on public.import_runs;
create policy import_runs_update_colaborador on public.import_runs for update to authenticated using (public.es_colaborador()) with check (public.es_colaborador());
grant select,insert,update on public.import_runs to authenticated;

create table if not exists public.ai_jobs (
  id bigint generated by default as identity primary key,
  partido_id bigint references public.partidos(id) on delete set null,
  video_id bigint references public.videos_partidos(id) on delete set null,
  estado text not null default 'pendiente' check (estado in ('pendiente','procesando','revision','completado','error','cancelado')),
  modelo text,
  modelo_version text,
  progreso numeric(5,2) not null default 0 check (progreso between 0 and 100),
  parametros jsonb not null default '{}'::jsonb,
  resultado jsonb not null default '{}'::jsonb,
  error text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);
create index if not exists idx_ai_jobs_estado_created on public.ai_jobs(estado,created_at desc);
create index if not exists idx_ai_jobs_partido on public.ai_jobs(partido_id);
alter table public.ai_jobs enable row level security;
drop policy if exists ai_jobs_select_colaborador on public.ai_jobs;
create policy ai_jobs_select_colaborador on public.ai_jobs for select to authenticated using (public.es_colaborador());
drop policy if exists ai_jobs_insert_colaborador on public.ai_jobs;
create policy ai_jobs_insert_colaborador on public.ai_jobs for insert to authenticated with check (public.es_colaborador());
drop policy if exists ai_jobs_update_colaborador on public.ai_jobs;
create policy ai_jobs_update_colaborador on public.ai_jobs for update to authenticated using (public.es_colaborador()) with check (public.es_colaborador());
grant select,insert,update on public.ai_jobs to authenticated;

create table if not exists public.ai_eventos (
  id bigint generated by default as identity primary key,
  job_id bigint references public.ai_jobs(id) on delete cascade,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  video_id bigint references public.videos_partidos(id) on delete set null,
  jugador_id bigint references public.jugadores(id) on delete set null,
  equipo_id bigint references public.equipos(id) on delete set null,
  tipo text not null,
  timestamp_ms bigint not null check (timestamp_ms>=0),
  frame integer check (frame is null or frame>=0),
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  track_id text,
  bbox jsonb,
  metadata jsonb not null default '{}'::jsonb,
  revisado boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_ai_eventos_partido_timestamp on public.ai_eventos(partido_id,timestamp_ms);
create index if not exists idx_ai_eventos_job on public.ai_eventos(job_id);
create index if not exists idx_ai_eventos_jugador on public.ai_eventos(jugador_id);
alter table public.ai_eventos enable row level security;
drop policy if exists ai_eventos_select_publico on public.ai_eventos;
create policy ai_eventos_select_publico on public.ai_eventos for select to anon,authenticated using (revisado=true);
drop policy if exists ai_eventos_select_colaborador on public.ai_eventos;
create policy ai_eventos_select_colaborador on public.ai_eventos for select to authenticated using (public.es_colaborador());
drop policy if exists ai_eventos_insert_colaborador on public.ai_eventos;
create policy ai_eventos_insert_colaborador on public.ai_eventos for insert to authenticated with check (public.es_colaborador());
drop policy if exists ai_eventos_update_colaborador on public.ai_eventos;
create policy ai_eventos_update_colaborador on public.ai_eventos for update to authenticated using (public.es_colaborador()) with check (public.es_colaborador());
drop policy if exists ai_eventos_delete_admin on public.ai_eventos;
create policy ai_eventos_delete_admin on public.ai_eventos for delete to authenticated using (public.es_admin());
grant select on public.ai_eventos to anon;
grant select,insert,update,delete on public.ai_eventos to authenticated;

create index if not exists idx_partidos_temporada_fecha on public.partidos(temporada_id,fecha,hora);
create index if not exists idx_partidos_estado_fecha on public.partidos(estado,fecha);

create or replace view public.v_global_summary with (security_invoker=true) as
select
 (select count(*) from public.clubes where activo) clubes,
 (select count(*) from public.equipos where activo) equipos,
 (select count(*) from public.jugadores where activo) jugadores,
 (select count(*) from public.partidos) partidos,
 (select count(*) from public.partidos where goles_local is not null and goles_visitante is not null) partidos_con_resultado,
 (select coalesce(sum(goles_local+goles_visitante),0) from public.partidos where goles_local is not null and goles_visitante is not null) goles,
 (select round(avg((goles_local+goles_visitante)::numeric),1) from public.partidos where goles_local is not null and goles_visitante is not null) promedio_goles,
 (select count(*) from public.partidos where planilla_url is not null) partidos_con_planilla,
 (select count(*) from public.videos_partidos) videos,
 (select count(*) from public.videos_partidos where procesado_ia) videos_procesados_ia;
grant select on public.v_global_summary to anon,authenticated;

create or replace view public.v_competition_catalog with (security_invoker=true) as
select e.temporada_id,t.nombre temporada,e.rama,e.categoria,e.division,
 count(*) filter(where e.activo) equipos,
 count(distinct p.id) partidos,
 count(distinct p.id) filter(where p.goles_local is not null and p.goles_visitante is not null) partidos_con_resultado,
 min(p.fecha) fecha_desde,max(p.fecha) fecha_hasta
from public.equipos e join public.temporadas t on t.id=e.temporada_id
left join public.partidos p on p.temporada_id=e.temporada_id and (p.local_equipo_id=e.id or p.visitante_equipo_id=e.id)
group by e.temporada_id,t.nombre,e.rama,e.categoria,e.division;
grant select on public.v_competition_catalog to anon,authenticated;

create or replace view public.v_data_quality_summary with (security_invoker=true) as
select
 (select count(*) from public.clubes where logo_url is null or btrim(logo_url)='') clubes_sin_logo,
 (select count(*) from public.clubes where abreviatura is null or btrim(abreviatura)='') clubes_sin_abreviatura,
 (select count(*) from public.clubes where ciudad is null or btrim(ciudad)='') clubes_sin_ciudad,
 (select count(*) from public.jugadores j where not exists(select 1 from public.planteles pl where pl.jugador_id=j.id)) jugadores_sin_plantel,
 (select count(*) from public.partidos where goles_local is null or goles_visitante is null) partidos_sin_resultado,
 (select count(*) from public.partidos where planilla_url is null) partidos_sin_planilla,
 (select count(*) from public.partidos where programacion_url is null and programacion_pdf_url is null) partidos_sin_fuente_programacion,
 (select count(*) from public.videos_partidos where not procesado_ia) videos_pendientes_ia,
 (select count(*) from public.import_revision where estado='pendiente') revisiones_importacion_pendientes;
grant select on public.v_data_quality_summary to anon,authenticated;

create or replace view public.v_standings with (security_invoker=true) as
with played as (
 select p.temporada_id,p.id partido_id,p.local_equipo_id equipo_id,p.goles_local gf,p.goles_visitante ga,
  (p.goles_local>p.goles_visitante)::int pg,(p.goles_local=p.goles_visitante)::int pe,(p.goles_local<p.goles_visitante)::int pp
 from public.partidos p where p.goles_local is not null and p.goles_visitante is not null
 union all
 select p.temporada_id,p.id,p.visitante_equipo_id,p.goles_visitante,p.goles_local,
  (p.goles_visitante>p.goles_local)::int,(p.goles_visitante=p.goles_local)::int,(p.goles_visitante<p.goles_local)::int
 from public.partidos p where p.goles_local is not null and p.goles_visitante is not null
), agg as (
 select temporada_id,equipo_id,count(*) pj,sum(pg) pg,sum(pe) pe,sum(pp) pp,sum(gf) gf,sum(ga) ga from played group by temporada_id,equipo_id
)
select e.temporada_id,e.id equipo_id,e.club_id,c.nombre club,e.rama,e.categoria,e.division,e.equipo_codigo,
 coalesce(a.pj,0)::bigint pj,coalesce(a.pg,0)::bigint pg,coalesce(a.pe,0)::bigint pe,coalesce(a.pp,0)::bigint pp,
 coalesce(a.gf,0)::bigint gf,coalesce(a.ga,0)::bigint ga,(coalesce(a.gf,0)-coalesce(a.ga,0))::bigint dif,
 (coalesce(a.pg,0)*2+coalesce(a.pe,0))::bigint puntos
from public.equipos e join public.clubes c on c.id=e.club_id
left join agg a on a.temporada_id=e.temporada_id and a.equipo_id=e.id where e.activo;
grant select on public.v_standings to anon,authenticated;

create or replace view public.v_player_totals with (security_invoker=true) as
select j.id jugador_id,j.nombre,j.apellido,pl.equipo_id,e.club_id,c.nombre club,e.rama,e.categoria,e.division,
 count(distinct pa.partido_id) partidos,coalesce(sum(pa.goles),0) goles,
 round(coalesce(sum(pa.goles),0)::numeric/nullif(count(distinct pa.partido_id),0),2) goles_por_partido,
 coalesce(sum(pa.exclusiones_2min),0) exclusiones_2min,coalesce(sum(pa.tarjeta_amarilla),0) amarillas,coalesce(sum(pa.tarjeta_roja),0) rojas
from public.jugadores j left join public.planteles pl on pl.jugador_id=j.id
left join public.equipos e on e.id=pl.equipo_id left join public.clubes c on c.id=e.club_id
left join public.participaciones pa on pa.jugador_id=j.id and (pl.equipo_id is null or pa.equipo_id=pl.equipo_id)
group by j.id,j.nombre,j.apellido,pl.equipo_id,e.club_id,c.nombre,e.rama,e.categoria,e.division;
grant select on public.v_player_totals to anon,authenticated;

commit;
